version: '3'
services:
  app:
    image: tggdocker/chat-github
    ports:
      - 8081:3000
    environment:
      - DATABASE_URL=mysql://root:12345678@localhost:3306/chat_app
      - OPENAI_API_KEY=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
      - CODE=goodboy
    volumes:
      - ./nextjs/files:/app
      - ./prisma/files:/app/prisma
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=chat_app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
    volumes:
      - ./mysql/data:/var/lib/mysql
    expose:
      - 3306
