version: "3"
services:
  app:
    image: tggdocker/chat-github:latest
    ports:
      - 80:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    restart: always
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 3306
  casdoor:
    image: casbin/casdoor:latest
    ports:
      - 8000:8000
    environment:
      RUNNING_IN_DOCKER: "true"
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./conf:/conf/

