name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create empty files
      run: |
        mkdir -p $HOME/.ssh/zhongbang
        touch $HOME/.ssh/zhongbang/apiclient_cert.pem
        touch $HOME/.ssh/zhongbang/apiclient_key.pem
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chat:$(date +%s)
